version: "3"

volumes:
  cnodp:
    driver: local
    external: false

services:
  cnodp:
    image: cnodp/wolves-${WOLF_SIZE}:latest
    container_name: cnodp-${WOLF_SIZE}
    working_dir: /home/precore
    tty: true
    ports:
     - ${EXPOSE_PORT}:8080
    volumes:
      - cnodp:/home/precore